runtime: php
env: flex
manual_scaling:
  instances: 1
env_variables:
  DATABASE_HOST: '130.211.247.213'
  DATABASE_USER: 'whiteboard'
  DATABASE_PASSWORD: 'u;Fq>5QPqVvAhsCy'
runtime_config:
    document_root: web